# .super-linter.yml

# Dit stelt in welke bestandstypen je wilt linten
linters:
  # Schakel de linters uit die je niet wilt gebruiken
  BASH: false
  CHECKOV: false
  GOOGLE_JAVA_FORMAT: true
  JAVA: true
  SHELL_SHFMT: false
  YAML_PRETTIER: true

# Specificeer hier andere configuraties voor je linters
