name: Java CI with Docker

on:
  push:
    branches:
      - master  # Trigger op push naar de master branch
  pull_request:
    branches:
      - master  # Trigger op pull request naar master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t webshopapi .

      - name: Tag Docker image
        run: |
          docker tag webshopapi:latest jonaseveraard/webshopapi:latest

  test:
    runs-on: ubuntu-latest
    needs: build  # Deze job wacht op de build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Load Test with k6
        uses: docker://grafana/k6:latest
        with:
          args: run ./tests/loadtest.js

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Deze job wacht op de test job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonaseveraard/webshopapi:latest

      - name: Start API container
        run: |
          docker run -d --name webshopapi -p 8080:8080 jonaseveraard/webshopapi:latest

      - name: Wait for API to be ready with wait-for-it
        run: |
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh localhost:8080 --timeout=60 --strict -- echo "API is up and running!"
