name: Java CI with Checkstyle

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22' 
          distribution: 'temurin'

      - name: Build with Maven
        env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn -B clean verify

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build Docker image
        run: |
          docker build -t webshopapi .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag webshopapi:latest jonaseveraard/webshopapi:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonaseveraard/webshopapi:latest

      - name: Start API container
        run: |
         docker run -d --name webshopapi -p 8080:8080 jonaseveraard/webshopapi:latest

      - name: Wait for API to be ready
        run: |
         until $(curl --output /dev/null --silent --head --fail http://localhost:8080/api/health); do
         printf '.'
         sleep 5
         done

      - name: Run Load Test with k6
        uses: docker://grafana/k6:latest
        with:
          args: run ./tests/loadtest.js
