name: Java CI with Checkstyle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'  # Specificeren van JDK 22
          distribution: 'temurin'

      - name: Echo secret key
        env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: echo "$SECRET_KEY" 

      - name: Build with Maven
        env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn -X clean verify

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run Tests
        run: mvn test
