name: Java CI with Checkstyle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job 1: Build en Test
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn -B clean package

      - name: Run Checkstyle
        run: mvn checkstyle:check

  # Job 2: Docker Build
  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t webshopapi .
      
      - name: Start API container
        run: docker run -d --name webshopapi -p 8080:8080 webshopapi:latest

      - name: Wait for API to be ready with wait-for-it
        run: |
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh localhost:8080 --timeout=60 --strict -- echo "API is up and running!"
