name: Java CI with Checkstyle

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22' 
          distribution: 'temurin'

      - name: Build with Maven
        env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn -B clean verify

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build Docker image
        run: |
          docker build -t webshop-api .

      - name: Tag Docker image
        run: |
          docker tag webshop-api:latest jonaseveraard/webshop-api:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonaseveraard/webshop-api:latest
