name: Java CI with Checkstyle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job 1: Build en Test
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn -B clean verify

      - name: Run Checkstyle
        run: mvn checkstyle:check

  # Job 2: Docker Build en Load Test
  docker-build-and-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t webshopapi .

      - name: Start API container
        run: docker run -d --name webshopapi -p 8080:8080 webshopapi:latest

      - name: Wait for API to be ready with wait-for-it
        run: |
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh localhost:8080 --timeout=60 --strict -- echo "API is up and running!"

      - name: Run Load Test with k6
        uses: docker://grafana/k6:latest
        with:
          args: run ./tests/loadtest.js

  # Job 3: Push naar Docker Hub
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag webshopapi:latest jonaseveraard/webshopapi:latest

      - name: Push Docker image to Docker Hub
        run: docker push jonaseveraard/webshopapi:latest
